codecov:
  max_report_age: off
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        informational: true
    patch: off

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

parsers:
  javascript:
    enable_partials: yes

github_checks:
  annotations: true

bundle_analysis:
  require_bundle_changes: "bundle_increase"
  bundle_change_threshold: "1Kb"
