name: 'Setup Elide'
description: 'Sets up the Elide runtime within GitHub Actions'
author: 'Elide'

inputs:
  version:
    description: 'Version'
    required: false
    default: 'latest'

  os:
    description: 'OS'
    required: false

  arch:
    description: 'Architecture'
    required: false

  target:
    description: 'Custom install path'
    required: false

  force:
    description: 'Force install'
    required: false

  export_path:
    description: 'Export to Path'
    required: false
    default: true

  custom_url:
    description: 'Custom Download URL'
    required: false

  token:
    description: 'GitHub Token'
    required: false

outputs:
  path:
    description: 'Path to Elide'

runs:
  using: node20
  main: dist/index.js
