name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: "Setup: Checkout"
        id: checkout
        uses: actions/checkout@v4

      - name: "Setup: PNPM"
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.0

      - name: "Setup: Node"
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: "Setup: Install Dependencies"
        id: npm-ci
        run: pnpm install

      - name: Check Format
        id: npm-format-check
        run: pnpm run format:check

      - name: Lint
        id: npm-lint
        run: pnpm run lint

      - name: Test
        id: npm-ci-test
        run: pnpm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with: {}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.path }}"
