name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  lint:
    name: "Check: Lint"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: "Setup: Checkout"
        id: checkout
        uses: actions/checkout@v4

      - name: "Setup: PNPM"
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.0

      - name: "Setup: Node"
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: "Setup: Install Dependencies"
        id: install
        run: pnpm install
  
      - name: Lint Code Base
        id: super-linter
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_JSCPD: false
